runtime: php81
entrypoint: serve index.php
# automatic_scaling:
#   # target_cpu_utilization: 0.65
#   # min_instances: 1
#   # max_instances: 15
#   # target_throughput_utilization: 0.5

# instance_class: F2

# runtime_config:
#   document_root: .
#   front_controller_file: index.php

